# Generated by Django 6.0.7 on 2026-08-07 10:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceablePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit Indian PIN code.', regex='^[1-9]\\d{5}$')])),
                ('area_name', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('cash_on_delivery_available', models.BooleanField(default=False)),
                ('estimated_delivery_days', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('free_shipping_minimum_order', models.DecimalField(decimal_places=2, default=Decimal('999.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviceable PIN code',
                'verbose_name_plural': 'Serviceable PIN codes',
                'ordering': ('state', 'city', 'pincode'),
            },
        ),
    ]
