# Generated by Django 5.1.7 on 2026-08-13 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_ebookpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='source_url',
            field=models.URLField(blank=True, help_text='Public-domain source URL, if applicable.'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(blank=True, upload_to='ebooks/private/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub'])]),
        ),
    ]
