# Generated by Django 5.1.7 on 2026-08-08 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="otp_type",
            field=models.CharField(
                choices=[
                    ("email_verify", "Email Verification"),
                    ("email_login", "Email Login"),
                    ("password_reset", "Password Reset"),
                    ("email_change", "Email Change"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
